name: admin_eat
description: Admin dashboard of the FYP project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.3
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  url_launcher: ^6.1.0
  fl_chart: ^0.50.1
  table_calendar: ^3.0.5
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/SignInSignUpimage.svg
    - assets/default_pic.png
    - assets/HomepageLogo.svg
    - assets/DashboardIcon.svg
    - assets/ChatIcon.svg
    - assets/FeedbackIcon.svg
    - assets/MessMenuIcon.svg

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/NexaLight.otf
          weight: 300
        - asset: assets/fonts/NexaRegular.otf
          weight: 400
        - asset: assets/fonts/NexaRegularItalic.otf
          style: italic
        - asset: assets/fonts/NexaBold.otf
          weight: 700